-- Google OAuth user and session storage.
-- Session tokens are generated by the backend and stored as SHA-256 hashes.

create table if not exists ojtflow.users (
    user_id text primary key,
    google_sub text not null unique,
    email text not null unique,
    email_verified boolean not null default false,
    display_name text,
    avatar_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    last_login_at timestamptz
);

create index if not exists idx_users_email
    on ojtflow.users(email);

create table if not exists ojtflow.sessions (
    session_id text primary key,
    user_id text not null references ojtflow.users(user_id)
        on delete cascade,
    token_hash text not null unique,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null,
    revoked_at timestamptz,
    last_seen_at timestamptz,
    user_agent text,
    ip_address inet,
    constraint sessions_token_hash_check check (token_hash ~ '^[0-9a-f]{64}$'),
    constraint sessions_expires_after_created check (expires_at > created_at)
);

create index if not exists idx_sessions_user_id
    on ojtflow.sessions(user_id);

create index if not exists idx_sessions_token_hash
    on ojtflow.sessions(token_hash);

create index if not exists idx_sessions_active_expires_at
    on ojtflow.sessions(expires_at)
    where revoked_at is null;
