-- Token-link invitations to join an organization workspace.
-- The raw invite token is generated by the backend and stored only as a SHA-256 hash.

create table if not exists ojtflow.organization_invitations (
    invitation_id text primary key,
    organization_id text not null references ojtflow.organizations(organization_id)
        on delete cascade,
    email text not null,
    role_key text not null,
    status text not null default 'pending',
    token_hash text not null unique,
    invited_by_user_id text not null references ojtflow.users(user_id),
    created_at timestamptz not null default now(),
    expires_at timestamptz not null,
    accepted_at timestamptz,
    accepted_by_user_id text references ojtflow.users(user_id),
    constraint organization_invitations_status_check
        check (status in ('pending', 'accepted', 'revoked', 'expired')),
    constraint organization_invitations_token_hash_check
        check (token_hash ~ '^[0-9a-f]{64}$')
);

create index if not exists idx_org_invitations_org_status
    on ojtflow.organization_invitations(organization_id, status, created_at desc);

create index if not exists idx_org_invitations_email
    on ojtflow.organization_invitations(lower(email));

create index if not exists idx_org_invitations_token_hash
    on ojtflow.organization_invitations(token_hash);
