import type { RetrievalPackage, RetrievalSearchPayload } from "../../../types";
import { humanize } from "../../../lib/utils";
import { searchAnswerReportFromPackage } from "./search-answer-report";
import {
  searchAnswerFallbackRemediation,
  searchAnswerStatus,
} from "./search-answer-status";
import type { SearchAnswerViewModel } from "./search-answer-types";
import {
  formatSearchAnswerCount,
  searchAnswerWarnings,
  stringFromRecord,
} from "./search-answer-warnings";

export function buildSearchAnswerViewModel(
  packageData: RetrievalPackage,
  submittedSearchPayload: RetrievalSearchPayload | null,
): SearchAnswerViewModel {
  const qualitySummary = packageData.quality_summary ?? null;
  const topHit = packageData.hits[0] ?? null;
  const actions = packageData.recommended_actions ?? [];
  const requiredBuckets = packageData.evidence_buckets?.filter((bucket) => bucket.required) ?? [];
  const missingBuckets = requiredBuckets.filter((bucket) => bucket.hit_count === 0);
  const warnings = searchAnswerWarnings(packageData);
  const remediation =
    packageData.remediation_summary ??
    stringFromRecord(packageData.handoff_context, "remediation_summary") ??
    searchAnswerFallbackRemediation(packageData);
  const status = searchAnswerStatus(packageData);
  const missingBucketLabels = missingBuckets.map((bucket) => bucket.label);

  return {
    actionCount: actions.length,
    metrics: [
      {
        detail: topHit
          ? `${humanize(topHit.evidence.source_type)} / ${topHit.evidence.trust_level}`
          : "Broaden scope or inspect inventory before treating this as evidence absence.",
        label: "Top evidence",
        value: topHit?.evidence.source_id ?? "No ranked source",
      },
      {
        detail: missingBuckets.length
          ? `Missing: ${missingBucketLabels.join(", ")}`
          : "Required evidence buckets are covered for this package.",
        label: "Required support",
        value: requiredBuckets.length
          ? `${requiredBuckets.length - missingBuckets.length}/${requiredBuckets.length} covered`
          : "No bucket policy",
      },
      {
        detail: actions[0]
          ? `${actions[0].title} / ${humanize(actions[0].action_type)}`
          : "No corrective action was generated by the quality policy.",
        label: "Backend actions",
        value: actions.length ? formatSearchAnswerCount(actions.length, "action") : "No action",
      },
    ],
    qualityScore: qualitySummary?.score ?? null,
    remediation,
    report: searchAnswerReportFromPackage(packageData, submittedSearchPayload, {
      missingBucketLabels,
      remediation,
      status,
      warningCount: warnings.length,
    }),
    status,
    warnings,
  };
}
