import type { RetrievalPackage, RetrievalSearchPayload } from "../../../types";
import { humanize } from "../../../lib/utils";

export type SearchAnswerStatus = {
  label: string;
  variant: "default" | "success" | "warning" | "destructive" | "muted";
};

export type SearchAnswerMetric = {
  detail: string;
  label: string;
  value: string;
};

export type SearchAnswerViewModel = {
  actionCount: number;
  metrics: SearchAnswerMetric[];
  qualityScore: number | null;
  remediation: string;
  report: Record<string, unknown>;
  status: SearchAnswerStatus;
  warnings: string[];
};

export function buildSearchAnswerViewModel(
  packageData: RetrievalPackage,
  submittedSearchPayload: RetrievalSearchPayload | null,
): SearchAnswerViewModel {
  const qualitySummary = packageData.quality_summary ?? null;
  const topHit = packageData.hits[0] ?? null;
  const actions = packageData.recommended_actions ?? [];
  const requiredBuckets = packageData.evidence_buckets?.filter((bucket) => bucket.required) ?? [];
  const missingBuckets = requiredBuckets.filter((bucket) => bucket.hit_count === 0);
  const warnings = searchAnswerWarnings(packageData);
  const remediation =
    packageData.remediation_summary ??
    stringFromRecord(packageData.handoff_context, "remediation_summary") ??
    searchAnswerFallbackRemediation(packageData);
  const status = searchAnswerStatus(packageData);
  const missingBucketLabels = missingBuckets.map((bucket) => bucket.label);

  return {
    actionCount: actions.length,
    metrics: [
      {
        detail: topHit
          ? `${humanize(topHit.evidence.source_type)} / ${topHit.evidence.trust_level}`
          : "Broaden scope or inspect inventory before treating this as evidence absence.",
        label: "Top evidence",
        value: topHit?.evidence.source_id ?? "No ranked source",
      },
      {
        detail: missingBuckets.length
          ? `Missing: ${missingBucketLabels.join(", ")}`
          : "Required evidence buckets are covered for this package.",
        label: "Required support",
        value: requiredBuckets.length
          ? `${requiredBuckets.length - missingBuckets.length}/${requiredBuckets.length} covered`
          : "No bucket policy",
      },
      {
        detail: actions[0]
          ? `${actions[0].title} / ${humanize(actions[0].action_type)}`
          : "No corrective action was generated by the quality policy.",
        label: "Backend actions",
        value: actions.length ? formatCount(actions.length, "action") : "No action",
      },
    ],
    qualityScore: qualitySummary?.score ?? null,
    remediation,
    report: searchAnswerReportFromPackage(packageData, submittedSearchPayload, {
      missingBucketLabels,
      remediation,
      status,
      warningCount: warnings.length,
    }),
    status,
    warnings,
  };
}

function searchAnswerStatus(packageData: RetrievalPackage): SearchAnswerStatus {
  if (!packageData.hits.length) return { label: "No evidence hit", variant: "destructive" };
  const qualityStatus = packageData.quality_summary?.status;
  if (qualityStatus === "blocked") return { label: "Blocked", variant: "destructive" };
  if (qualityStatus === "review") return { label: "Needs review", variant: "warning" };
  if (packageData.trace.warnings.length) return { label: "Review warnings", variant: "warning" };
  return { label: "Evidence ready", variant: "success" };
}

function searchAnswerFallbackRemediation(packageData: RetrievalPackage): string {
  const topAction = packageData.recommended_actions?.[0];
  if (topAction) return `${topAction.title}: ${topAction.description}`;
  const qualityAction = packageData.quality_summary?.top_action;
  if (qualityAction) return qualityAction;
  if (!packageData.hits.length) return "Broaden search scope or inspect source inventory.";
  return "Review the top evidence hit, readiness score, and source provenance before using this package.";
}

function searchAnswerReportFromPackage(
  packageData: RetrievalPackage,
  submittedSearchPayload: RetrievalSearchPayload | null,
  summary: {
    missingBucketLabels: string[];
    remediation: string;
    status: SearchAnswerStatus;
    warningCount: number;
  },
) {
  const topHit = packageData.hits[0] ?? null;
  return {
    report_type: "retrieval_search_answer",
    version: 1,
    generated_at: new Date().toISOString(),
    query: submittedSearchPayload?.query ?? null,
    status: summary.status.label,
    remediation_summary: summary.remediation,
    interpretation: packageData.interpretation ?? fallbackInterpretation(packageData),
    standard_search_plan: packageData.standard_search_plan ?? null,
    medical_search_hints: searchHintsFromPackage(packageData),
    diversity: packageData.diversity ?? null,
    readiness: packageData.quality_summary,
    warnings: {
      count: summary.warningCount,
      trace: packageData.trace.warnings,
      coverage: packageData.coverage?.warnings ?? [],
    },
    required_support: {
      missing_buckets: summary.missingBucketLabels,
      buckets: packageData.evidence_buckets ?? [],
    },
    top_evidence: topHit
      ? {
          evidence_id: topHit.evidence.evidence_id,
          source_id: topHit.evidence.source_id,
          source_type: topHit.evidence.source_type,
          trust_level: topHit.evidence.trust_level,
          claim: topHit.evidence.claim,
          score: topHit.score,
          match_explanation: topHit.match_explanation ?? null,
        }
      : null,
    recommended_actions: (packageData.recommended_actions ?? []).slice(0, 6),
  };
}

function fallbackInterpretation(packageData: RetrievalPackage) {
  const topHit = packageData.hits[0] ?? null;
  const requiredBuckets = packageData.evidence_buckets?.filter((bucket) => bucket.required) ?? [];
  const missingRequiredBuckets = requiredBuckets.filter((bucket) => bucket.hit_count === 0);
  return {
    source: "frontend_search_answer_fallback",
    status: topHit
      ? missingRequiredBuckets.length
        ? "support_gaps"
        : "ready_to_review"
      : "no_ranked_evidence",
    summary: packageData.remediation_summary ?? searchAnswerFallbackRemediation(packageData),
    top_evidence_id: topHit?.evidence.evidence_id ?? null,
    top_source_id: topHit?.evidence.source_id ?? null,
    matched_terms: topHit?.matched_terms.slice(0, 6) ?? [],
    required_bucket_count: requiredBuckets.length,
    covered_required_bucket_count: requiredBuckets.length - missingRequiredBuckets.length,
    missing_required_buckets: missingRequiredBuckets.map((bucket) => bucket.label),
    warning_count: searchAnswerWarnings(packageData).length,
  };
}

function searchHintsFromPackage(packageData: RetrievalPackage): unknown[] {
  const queryAnalysis = packageData.handoff_context.query_analysis;
  if (!queryAnalysis || typeof queryAnalysis !== "object" || Array.isArray(queryAnalysis)) {
    return [];
  }
  const hints = (queryAnalysis as Record<string, unknown>).search_hints;
  return Array.isArray(hints) ? hints.slice(0, 8) : [];
}

function searchAnswerWarnings(packageData: RetrievalPackage): string[] {
  return [
    ...(packageData.trace.warnings ?? []),
    ...((packageData.coverage?.warnings ?? []) as string[]),
  ].filter((warning) => warning.trim());
}

function stringFromRecord(record: Record<string, unknown>, key: string): string | null {
  const value = record[key];
  return typeof value === "string" && value.trim() ? value : null;
}

function formatCount(count: number, singular: string) {
  return `${count} ${singular}${count === 1 ? "" : "s"}`;
}
